[package]
name = "masto-thread-renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2" }
askama = { git = "https://github.com/djc/askama.git", rev = "8142963", features = [
    "config",
    "with-rocket",
    "mime",
    "mime_guess",
] }
askama_rocket = { git = "https://github.com/djc/askama.git", rev = "8142963" }

[build-dependencies]
npm_rs = "0.2.1"
